oricutron.cfg
A typo error in the config file where the key for the jasmin ROM path is incorrect, the code search for jasminrom, the config provice "jasmnrom". 
I just corrected the default config file to use the correct name
(Thanks to _DBug_ for finding there were an issue when using non standard path for the jasmin rom)
=> Typo: Correct key is "jasminrom" and not "jasmnrom"

Makefile
The Open Pandora has a few Oricutron fans.  This PR makes it easier for them to build Oricutron on the Pandora itself, using the Pandoras CDevTools (CDEVTOOLS.PND), without too much fuss.
`
$ PLATFORM=pandora make
`
.. resuilts in ./oricutron built with SDL support, no GTK, no GL.
(GL support for Pandora will come in a separate PR..)
=> Add PLATFORM=pandora configuration

ReadMe.txt, plugins/ch376/ch376.c
This pull request is to add 2 new emulated command of CH376 chip : 
1) Create a folder
2) Delete a file.
Tested under WIN32 (for my part). For AmigaOS, Morphos, et AROS, i think Offset did the test in his own emulator (ACE)
=> CH376 emulation improve

plugins/ch376/ch376.c
Note: new system_directory_delete() function tested on Linux OS only
=> Improve CH376 emulation + add CREATE_DIR & ERASE_FILE support for Linux

plugins/ch376/ch376.c
Improve ch376 emulation with pattern support for CMD_FILE_OPEN: not only "*" but also "file*"
=> CH376: Open pattern

.travis.yml, configure
Here is the initialization for travis ci.
Is it possible to activate in travis the ci for : pete-gordon/oricutron ? @pete-gordon 
I will add url on README.md (for build passing icon). For instance, it does not compile under Linux but assinie had corrected this in the last pull request
=> travis management

gui.c, machine.c
No platform specific code.
All Oric/Atmos configurations with or without Microdisk/Jasmin supported
No Pravetz support added because I don't know if pravetz.extension must be take into account or not and how.
Correction of a little bug for the  CH376 option in the configuration menu (no check mark displayed the first time even if ch376 is on)
=> Add CH376 support for Oric & Atmos (not Pravetz)

.gitignore
The `.gitignore` entries for MSVC files were only valid for VS2015. This change allows subdirectories at any level within `msvc` to also be targeted by the ignore entries.
The trailing slashes allow ignoring directories only.
=> Fix .gitignore not applying to VS2017 files

6502.c
illegal opcodes DOP/TOP are not handled properly, they do not "eat" their operand.
Found by Symoon from defence-force.org, see [here](http://forum.defence-force.org/viewtopic.php?f=22&t=1957)
=> Fix DOP/TOP illegal opcodes

monitor.c
BRK is disassembled as an immediate opcode but assembled as an implicit 1 byte instruction.
This PR fix the assembler part.
=> Fix the embedded assembler: BRK is a 2 bytes instruction

system_sdl.c
This moves the window back to the center of the display
instead of to (0, 0) when exiting fullscreen mode, which
has the side effect of hiding the title bar if it is present.
As far as I can tell, Oricutron is meant to remember the coordinates of the window when entering fullscreen mode, and restore the window to those coordinates after exiting it. However it doesn't seem to be fully implemented and as a result, the window is placed at (0, 0). Instead of outright removing the mechanism to save the coordinates, this adds an extra bit of logic that could be removed later if the desired functionality is fully implemented.
=> Recenter the window when exiting fullscreen mode

disk.c
Tested with Sedoric's _INIT_ command and FTDos's _!"FORMAT"_ command.
Can someone review/test the patch before the merge?
__Note:__ the header of the disk file is not overwritten (you can format a double sided disk image as a single sided one, but the header will report a double sided disk)
=> Add WRITE TRACK support to FDC

via.c
If you try to print a filtered character, the Acknoledge bit is raised but can't be lowered because the prclock timer is 0 in this case/
**Bug evidence:** (note the **;** at the end of the line)
```LPRINT CHR$(254);```
Same issue if you try to **LPRINT** something after you **CLOAD** a program (probably related to the reconfiguration of the VIA by the K7 routines in the ROM).
I moved the _"emulate ack signal"_ block to the end of the function because this signal must always be emulated even if the **printenable** flag is false.
=> Bugfix: CA1 raised but never lowered when printing filtered characters

ReadMe.txt
#148 added read and write track; I also corrected a spelling error (trough -> through), a couple of negligible grammar points and verified the capitalisation of the macOS menu item against the real thing. I didn't want to do a big edit as that's none of my business, but I felt like the disk text being incorrect made it worth doing _something_.
=> Minor copy edits to readme.txt, primarily re: disk

6502.c
When D flag is set, calculation result and flags for ADC and SBC instructions are incorrect even for valid BCD values.
This patch fix SBC and ADC instructions when D flag is set.
Verified with Klaus Dormann decimal test: https://github.com/Klaus2m5/6502_65C02_functional_tests/blob/master/6502_decimal_test.a65
=> Fix decimal mode

disk.c
Quick patch to improve track scan.
Search for $A1 $A1 $A1 $FE instead of just $FE to find the beginning of a sector.
See discussion here https://forum.defence-force.org/viewtopic.php?f=8&t=2248
=> disk: improve ID mark search

CMakeLists.txt, ReadMe.txt, monitor.c
Hi,
I added a memory search functionnality. I did it to hack some games and finally finish them !
Here's a quick doc : 
- launch the game and check for lives number
- launch monitor (F2) execute **ms <lives#>**
- return to game
- die
- relaunch monitor and execute **mr <lives#-1>**
- show memory addresses with **p** command
At this point you should get one or more memory match (refine more if necessary)
now you should know where the lives counter is in memory, just do a **mm <memory_address> <new lives#>** to set new lives number and you're done.
new commands : 
- ms [memory search]
- mr [memory search refine]
- p [print found memory locations]
The search is made in free ram (0x500-0x97FF)
Hope you'll like it :)
=> Add monitor memory search

Makefile
This fixes a build error I encountered on macOS Sonoma with homebrew sdl2.
The fix is to link against Cocoa framework.
With the fix I can build using "make SDL_LIB=sdl2".
=> Fix linker error when building with sdl2 on macOS

gui.c, main.c, system.h
Purpose of this change:
* To make Oricutron runnable without cd'ing to its directory first
* To support relative paths with the -t option
* On macOS, to help command line users by not requiring a bundled app, allow "./oricutron" in the source directory much like under Linux.
Code changes:
* Factor out FILEPREFIX from ROMPREFIX and IMAGEPREFIX constants
* Apply FILEPREFIX for all filenames in oricutron.cfg which was done previously only for the keymap path
* Let function get_fileprefix() replace the FILEPREFIX constant, and use run-time concatenation instead of compile-time
* For Linux let get_fileprefix() return program binary's directory
* For macOS, let get_fileprefix() return parent of .app bundle if the program is bundled, otherwise do as in Linux.
=> Revise path handling to address issue #188

LICENSE.txt
I added a specific LICENSE.txt so that folks don't need to refer to the source headers and to make the license clear for package builders and distributors.
=> Add LICENSE.txt to the project: GPLV2, as per source headers.
